DELETE http://localhost:3003/api/blogs/61107db0af352f172a9b4dc7
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOiI2MTEwMWI0NmMxZTk4ODUwN2YxNTcxYjYiLCJpYXQiOjE2Mjg0NzA3NTZ9.KDLt-37kdpIRuxabdpCO78Av4p463kK4AQ3oyV_SNA0