DELETE http://localhost:3003/api/gatherings/6133dcfa3055522b6c803561
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRlcmVrIiwiaWQiOiI2MTMzZDYyNTBhODRiODI5NjVkMzBjZmIiLCJpYXQiOjE2MzA3ODcxNTJ9.YCXkwAs_jkUoIkv7PPgx-AudimQENrRRp945LKTBZN0
